#!/usr/bin/env python3
"""
Generate dorico-instructions.md and sibelius-instructions.md from the polish
run, explaining what changed at the style level and how a Dorico or Sibelius
user would apply equivalent settings in their own project.

Usage: write_instructions.py changes.json residual.json style_preset out_dir/
"""
import argparse
import json
import sys
from pathlib import Path


DORICO_TEMPLATE = """# Polish Report: Dorico Engrave-Mode Instructions

**Style preset applied:** {preset}
**Total content changes:** {change_total}
**Residual issues (manual fix needed):** {residual_total}

This score has been re-engraved through MuseScore with the `{preset}` style.
Most layout / collision issues are already fixed in `polished.pdf`. The lists
below tell you how to either (a) re-import the polished MusicXML into Dorico
and accept the new layout, or (b) replicate the settings manually in your
current Dorico project.

## Option A: Re-import polished MusicXML (recommended)

1. In Dorico, File > Import > MusicXML. Select `polished.musicxml`.
2. Dorico will recreate the project with the polished layout. You may lose
   Dorico-specific Engrave mode overrides. Save this as a new flow or new
   project to preserve your original as backup.
3. Review pages. The re-engrave has already resolved most collision,
   spacing, and staff-distance issues.

## Option B: Apply equivalent settings in your existing Dorico project

Open **Library > Engraving Options** and adjust:

### Notes
- **Beams > Slope > Beam angle limits**: preserve default (Dorico uses Gould-style beams by default)
- **Notes > Note spacing > Default space for note**: 4 1/4 spaces (moderate) or 4 1/2 (strict)
- **Accidentals > Horizontal spacing > Minimum distance**: 0.3 (moderate) or 0.35 (strict)

### Dynamics
- **Dynamics > Design > Minimum gap from staff**: 1.0 spaces
- **Dynamics > Vertical position > Default distance below bottom staff**: 3.5 spaces

### Rehearsal marks
- **Rehearsal marks > Design > Padding inside border**: 0.5 spaces (moderate) or 0.75 (strict)
- **Rehearsal marks > Position > Default gap above top staff**: 3.5 spaces

### Tempo
- **Tempo marks > Position > Default gap above top staff**: 4 spaces

### Staves / systems
- **Vertical spacing > Ideal gap between staves in a system**: 7 spaces (moderate) / 8 (strict)
- **Vertical spacing > Ideal gap between systems**: 9 spaces (moderate) / 10 (strict)

### Rests
- **Rests > Multi-bar rests > Minimum number of bars**: 2

## Changes made by re-engrave

{changes_summary}

## Residual issues (re-engrave could not fix, manual attention needed)

{residual_summary}

---

_Generated by music-engraving-polisher-dorico-sibelius._
"""


SIBELIUS_TEMPLATE = """# Polish Report: Sibelius Engrave Instructions

**Style preset applied:** {preset}
**Total content changes:** {change_total}
**Residual issues (manual fix needed):** {residual_total}

## Option A: Re-import polished MusicXML (recommended)

1. In Sibelius, File > Open. Select `polished.musicxml`. Sibelius will
   ask about MusicXML import options; accept defaults.
2. Sibelius recreates the layout. Save the new file under a new name.

## Option B: Apply equivalent house style in your existing Sibelius file

Open **House Style > Engraving Rules** and adjust:

### Notes and rests
- **Note Spacing > Minimum space**: 1.2 spaces (moderate) / 1.4 (strict)
- **Accidentals > Default gap**: 0.22 (moderate) / 0.25 (strict)

### Dynamics
- **Dynamics > Distance from staff**: 3.5 spaces
- **Dynamics > Minimum gap from other objects**: 0.5 (moderate) / 1.0 (strict)

### Rehearsal marks
- **Text Styles > Rehearsal Marks > Frame > Padding**: 0.5 (moderate) / 0.75 (strict)

### Staves
- **Staves > Default gaps above first and between staves**: 7 (moderate) / 8 (strict)

### Beams
- **Beams and Stems > Default stem length**: 3.5 spaces
- **Beams and Stems > Beam angle > Maximum slope**: 3 spaces

## Changes made by re-engrave

{changes_summary}

## Residual issues (re-engrave could not fix, manual attention needed)

{residual_summary}

---

_Generated by music-engraving-polisher-dorico-sibelius._
"""


def format_changes(changes_data):
    if not changes_data or not changes_data.get("changes"):
        return "_No musical-content changes. Polish was style-only (layout/spacing only)._"

    by_kind = changes_data.get("summary", {}).get("by_kind", {})
    lines = []
    for kind, count in sorted(by_kind.items()):
        lines.append(f"- **{kind}**: {count} instance(s)")
    return "\n".join(lines)


def format_residual(residual_data):
    if not residual_data or not residual_data.get("issues"):
        return "_No residual issues detected._"

    issues = residual_data["issues"]
    lines = []
    for i, issue in enumerate(issues[:50], start=1):
        lines.append(f"{i}. **{issue.get('kind')}** [{issue.get('severity')}] "
                     f"p.{issue.get('part', 'score')} m.{issue.get('measure', '?')}: "
                     f"{issue.get('detail', '')}")
        if issue.get("fix"):
            lines.append(f"   *Fix:* {issue['fix']}")
    if len(issues) > 50:
        lines.append(f"\n_... {len(issues) - 50} more issues in residual_issues.json_")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("changes_json", type=Path)
    ap.add_argument("residual_json", type=Path)
    ap.add_argument("preset")
    ap.add_argument("out_dir", type=Path)
    args = ap.parse_args()

    changes = json.loads(args.changes_json.read_text()) if args.changes_json.exists() else {}
    residual = json.loads(args.residual_json.read_text()) if args.residual_json.exists() else {}

    ctx = {
        "preset": args.preset,
        "change_total": changes.get("summary", {}).get("total_changes", 0),
        "residual_total": residual.get("total", 0),
        "changes_summary": format_changes(changes),
        "residual_summary": format_residual(residual),
    }

    args.out_dir.mkdir(parents=True, exist_ok=True)
    (args.out_dir / "dorico-instructions.md").write_text(DORICO_TEMPLATE.format(**ctx))
    (args.out_dir / "sibelius-instructions.md").write_text(SIBELIUS_TEMPLATE.format(**ctx))
    print(f"Wrote dorico-instructions.md + sibelius-instructions.md to {args.out_dir}")


if __name__ == "__main__":
    main()
